// Current
export const CURRENT_SELECT_COIN = "CURRENT_SELECT_COIN"

// Stocks
export const STOCKS_GET = "STOCKS_GET"
export const STOCKS_RECEIVED = "STOCKS_RECEIVED"
export const STOCKS_SET_FILTER = "STOCKS_SET_FILTER"

// Fear and greed index
export const GREED_GET = "GREED_GET"
export const GREED_RECEIVED = "GREED_RECEIVED"

// Chart
export const COINS_GET = "COINS_GET"
export const COINS_RECEIVED = "COINS_RECEIVED"
export const CHART_GET = "CHART_GET"
export const CHART_RECEIVED = "CHART_RECEIVED"

// Stocks
export const PREDICTIONS_GET = "PREDICTIONS_GET"
export const PREDICTIONS_RECEIVED = "PREDICTIONS_RECEIVED"
export const PREDICTION_CREATE = "PREDICTION_CREATE"
export const PREDICTION_UPDATE = "PREDICTION_UPDATE"
export const PREDICTION_REMOVE = "PREDICTION_REMOVE"
export const PREDICTION_SET_POPUP = "PREDICTION_SET_POPUP"
export const PREDICTIONS_SET_FILTER = "PREDICTIONS_SET_FILTER"

// News
export const NEWS_GET = "NEWS_GET"
export const NEWS_RECEIVED = "NEWS_RECEIVED"